<?php

$runy =[

"Home"=>"Omuka",
"Settings"=>"Okuhindura",
"Profile"=>"Endaga",
"Move on"=>"Gumizamu",
"Farm"=>"Eirisizo",
"Agriculture"=>"Okuhinga",
"Village"=>"Ekyaaro",
"Back"=>"Garukayo",
"Edit"=>"Hindura",
"Web"=>"Kanyabitimba",
"Pages"=>"Empapura",
"Users"=>"Abakozesa",
"Sacco"=>"Sacco",
"Group"=>"Akakungu",
"Association"=>"Orwetereine",
"Files"=>"Fayilo",
"File"=>"Eibikiro",
"Electricity"=>"Amashanyaraze",
"Water"=>"Amaizi",
"Farmer"=>"Omuhingi",
"Administrator"=>"Omwami",
"Manager"=>"Kareebi",
"Search"=>"Ronda",
"Videos"=>"Entambi zebishushani",
"Images"=>"Ebishushani",
"Chair"=>"Entebe",
"Computer"=>"Kanyabwengye",
"Cable"=>"Eirundo",
"Wire"=>"Ewaya",
"rope"=>"omuguha",
"login"=>"Okwikirizibwa",
"logout"=>"Okurugamu",
"register"=>"yehandikise",
"product"=>"ekirugwamu",
"District"=>"Disturikiti",
"Located"=>"Erikushangwa",
"Please wait"=>"Rindaho kakye",
"Welcome"=>"Twakwakira",
"Hi"=>"Nakuramutsya",
"Location"=>"Neshangwa",
"server"=>"eibiko",
"notifications"=>"obukule",
"Terms"=>"Engyendererwaho",
"Conditions"=>"Oburomborombo",
"Crops"=>"Ebihingwa",
"Animals"=>"Enyamishwa",
"animal"=>"ekinyamishwa",
  "goat"=>"embuzi",
  "gnuts"=>"ebinyoobwa",
  "rice"=>"omuceeri",
"beans"=>"ebihimba",
"maize"=>"ebicoori",
  "millet"=>"oburo",
  "sorghum"=>"omugusha",
  "sweet potatoes"=>"ebitakuri",
  "irish potatoes"=>"emondi",
  "bananas"=>"ebitookye",
  "banana plantation"=>"orutookye",
  "garden"=>"omusiri",
]

?>
